# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_renewal <- function(time_vec, modulant_vec, sigma, Q) {
    .Call(`_renewr_simulate_renewal`, time_vec, modulant_vec, sigma, Q)
}

simulate_renewal_orig <- function(time_vec, modulant_vec, shape, k) {
    .Call(`_renewr_simulate_renewal_orig`, time_vec, modulant_vec, shape, k)
}

simulate_renewal_flexible <- function(time_vec, modulant_mat_flat, groups_vec, shape_vec, k_vec, n_ind, n_samples, max_x, use_samples, start_time, seed_events) {
    .Call(`_renewr_simulate_renewal_flexible`, time_vec, modulant_mat_flat, groups_vec, shape_vec, k_vec, n_ind, n_samples, max_x, use_samples, start_time, seed_events)
}

